import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

interface Props {
    children: JSX.Element[] | JSX.Element;
    title: string | null;
}

export default function Layout({ children, title }: Props): JSX.Element {
    return (
        <>
            <Head>
                <title>{title ? `${title} Spes` : "Spes"}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main>{children}</main>
            <Footer/>
        </>
    );
}
