import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

interface Props {
    children: JSX.Element[] | JSX.Element;
    title?: string | null;
    showHeader?: boolean;
    showFooter?: boolean;
}

export default function Layout({
    children,
    title,
    showHeader,
    showFooter,
}: Props): JSX.Element {
    return (
        <>
            <Head>
                <title>{title ? `${title} - Spes` : "Spes"}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {showHeader && <Header />}

            <main className="w-[100vw] h-[100vh] font-custom-family overflow-auto no-scrollbar">{children}</main>

            {showFooter && <Footer />}
        </>
    );
}
