import Head from "next/head";


interface Props {
    children: JSX.Element [] | JSX.Element
    title: string | null
}

export default function Layout({children , title} : Props): JSX.Element {
  return (
    <>
      <Head>
        <title>{title ? `${title} Spes` : 'Spes'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className=" bg-red-900 text-white">Header</header>
      <main>{children}</main>
      <footer>Footer</footer>
    </>
  );
}
